### ISSUE TITLE
History state

### ISSUE THREAD

**Issue by AndersGM** [Profiscience/knockout-contrib#107]
In the router package, the default behavior of popstate is prevented, and thus the state is not updated. Therefor the history.state cannot really be used (even though it works, as far is I can see, with hashbang:true). 
Are there any reason for not replacing current state with the state received from the event?
I can of course make a pull request if you are interested.

Thanks for your great work!
Anders

**Comment by caseyWebb** [comment]
No particular reason. Added in the PR above, and published in the latest rc.
