### ISSUE TITLE
Lazy loading with dynamic routes

### ISSUE THREAD

**Issue by jamiemcl** [Profiscience/knockout-contrib#113]
I've been trying to get your lazy loading solution working for a large project I'm working on and have come across a few problems. The project currently uses history and crossroads for routing, and the main route defined at the app-root component is as follows:

```typescript
const routes: Route[] = [
    { url: `${Global.AppRoot + Global.AppRouterRoot}/{schema}/:location:/:component:/:id:/` }
];
```

Would it be possible to use this route with this knockout router and navigate to the dynamic component that is specified in the URL? 

If I am to follow the lazy loading example exactly, it would mean me having to specify the exact names of the components per route, instead of them being dynamically registered. This would mean me needing to write a lot of repeated code for a large project. I understand that the plugin included in the example you've provided can be extended but I can't see a way for me to access the route's URL directly to pull out the component name from it.

I'm obviously a newbie to this router, so any info or guidance is much appreciated.

Jamie

**Comment by caseyWebb** [comment]
Because you're only registering one route, you can actually just use a single middleware function for this.

> NOTE: The middleware is the function being returned by the plugin in the example. Since the component name is dynamic, you don't need to curry it w/ a plugin.

> NOTE: What is not shown in the original example is that the first argument to the [middleware](https://github.com/Profiscience/knockout-contrib/blob/master/packages/router/docs/middleware.md) is a the [route context](https://github.com/Profiscience/knockout-contrib/blob/master/packages/router/docs/context.md). This is relevant because we can get various path information, including just the parsed bits with `ctx.params`

```typescript
const dynamicComponentMiddleware: SimpleMiddleware = async (ctx: Context) => {
  // You *really* want to have some hardcoded prefix OR use the much more complicated require.context
  // otherwise webpack will include a manifest that contains EVERY file in the project which bloats the
  // bundle significantly
  //
  // For example, using import(someVariable) means webpack has to assume that "someVariable" can be ANYTHING.
  // By including the './components' directory prefix, we can at least limit the manifist to only contain files
  // in that directory.
  //
  // Using require.context will result in the best bundle size, but your project must follow strict conventions.
  // In our case, we use it to register any file matching `./components/*/index.ts` and it looks something like...
  //
  // const context = require.context('./', true, /\.\/[^/_]+\/index\.ts$/)
  // context.keys().forEach((c) => {
  //   const name = c.match(/\.\/([^/_]+)\/index\.ts$/)[1]
  //   ko.components.register(name, { ...context(c) })
  // })
  const componentName = ctx.params.component
  const componentDir = ctx.params.location
  const componentConfig = await import(`./components/${componentDir}/${componentName}`)

  // register the component if this is the first time it's being hit
  if (!ko.components.isRegistered(componentName)) {
    ko.components.register(componentName, componentConfig)
  }

  // tell the router which component to use
  ctx.route.component = componentName
}

Router.use(dynamicComponentMiddleware)
```

If possible though, I'd recommend against this pattern because you lose _a lot_ of flexibility, a **major** one being nested routing. This pattern pretty much precludes you from using any of the more powerful features in the router.

Something else you may consider is using the [component plugin](https://github.com/Profiscience/knockout-contrib/tree/master/packages/router.plugins.component) in place of where you'd normally do `ko.components.register`. This is the idiomatic usage (and the pattern we use internally with _very large_ SPAs), an example of which you can find [here](https://github.com/caseyWebb/knockout-realworld/tree/master/src/views) (parts of this repo are outdated, but everything in the `views` directory is the current recommended usage).

**Comment by caseyWebb** [comment]
Feel free to re-open if you need additional help. I'm also available in the [gitter channel](https://gitter.im/profiscience/ko-component-router).
