### ISSUE TITLE
(router) Routes not reloaded when navigated to with different parameters

### ISSUE THREAD

**Issue by emikoshi** [Profiscience/knockout-contrib#142]
**Package(s)**
 - router => @profiscience/knockout-contrib-router@2.0.0-rc.9

**Describe the bug**
I'm not sure if this is intended behavior after the latest update to rc9 or not. I did notice this commit: https://github.com/Profiscience/knockout-contrib/commit/6c06eb3.

When on a route, say **/customers/23/info** and then there is some action on that route `Router.update(//customers/56/info);`, no errors are thrown and it stays on the original route.

**Expected behavior**
I'd expect the router to update to the the latest route specified with `Router.update`. Fwiw, this was working prior to rc9 ( I was on rc8 before this, I even rolled back to verify ). The workaround is to currently pass `{ force: true }`.

**Desktop (please complete the following information):**
 - Latest stable version of Chrome

**Additional context**
Again I'm not sure if this is now the intended behavior or not now. Any insight would be greatly appreciated.

**Comment by caseyWebb** [comment]
nope, that's a bug.
