### ISSUE TITLE
Router: "path" and "activePath" bindings could have an option to match child route paths as well.

### ISSUE THREAD

**Issue by gandrisl** [Profiscience/knockout-contrib#64]
This is a feature suggestion for Router.
I. e. having route structure.
|-- /page1
|-- /page2
     |--- /
      |--- /tab2

In order to create a menu for top level paths there is a need to have a bindings "path" and "activePath" that would also match child routes. Current implementation of "activePath" matches full path only, binding doesnt add active path class to "/page2" anchor when current path is "/page2/tab2". This could be an option for an existing binding handlers (both "path" and "activePath"), i.e. `<a data-bind="path: '/page2', matchChildrenAsActive: true">page2</a>`

**Comment by caseyWebb** [comment]
+1 for implementing this, but I'd like the API to be something like `data-bind="path: '/page2/*'"`

**Comment by caseyWebb** [comment]
After more thought, making this the default behavior didn't make sense. Take the following example...

```
new Route('/users', {
  children: [
    new Route('/', ...),
    new Route('/:id', ...)
  ]
})
```

In this case, a path binding to `/users` will (as expected) navigate to the first child route. However, it's ambiguous as to if this is matching the parent (intermediate), or child (terminal) route for the purposes of determining whether or not to add the `active-path` class.

For that reason, this functionality has been added via a wildcard. The wildcard **must** be the last character, and it **must** be immediately preceeded by a `/`.

It is only used for determining whether or not to apply the active-path class, and will be disregarded for the purposes of navigating.

For example, to create a path binding which will have the `active-path` class applied for any child route of `/users`, simply do `path: '/users/*'.

**Comment by caseyWebb** [comment]
Install with `yarn add @profiscience/knockout-contrib@rc` (rc b/c the latest version of the router requires Knockout 3.5.0-rc).
