### ISSUE TITLE
Plugins have unmet peer dependencies

### ISSUE THREAD

**Issue by troynguyen-unl** [Profiscience/knockout-contrib#67]
When installing `@profiscience/knockout-contrib-router-plugins-title`, I am given the following warning:

```
warning "@profiscience/knockout-contrib-router-plugins-title@1.0.0-alpha.7" has incorrect peer dependency "@profiscience/knockout-contrib-router@^2.0.0-4".
```

My package.json is as follows:
```
{
  "version": "1.0.0",
  "name": "asp.net",
  "dependencies": {
    "@profiscience/knockout-contrib-router": "^1.2.0",
    "@profiscience/knockout-contrib-router-plugins-title": "^1.0.0-alpha.7"
    ...
  },
  "devDependencies": {
    ...
  },
  "scripts": {
    ...
  }
}

```

Why is this happening?

**Comment by caseyWebb** [comment]
install `@profiscience/knockout-contrib-router@next`

It's not published as `latest` because it requires knockout 3.5.0-beta. I'm not sure just how long 3.5.0 is expected to stay in beta.

**Comment by troynguyen-unl** [comment]
Thanks! That fixed it!
