### ISSUE TITLE
Running router tests on windows machine gives an error

### ISSUE THREAD

**Issue by gandrisl** [Profiscience/knockout-contrib#78]
Tried running "test:router" script and got error.

![image](https://user-images.githubusercontent.com/23049209/39287812-1413af68-492e-11e8-885a-1fa7080e2fae.png)

Any ideas on how to fix it?

**Comment by gandrisl** [comment]
More details on setup.
node version: 8.11.1
yarn version: 1.3.2

**Comment by caseyWebb** [comment]
I'll try this out in the WSL when I have access to a Windows machine. If that works, this will be a #wontfix with PRs welcomed.
