### ISSUE TITLE
"component" plugin doesnt wait for queued promises on a context before creating instance of a view-model

### ISSUE THREAD

**Issue by gandrisl** [Profiscience/knockout-contrib#87]
When following config is provided to a Route class, ComponentViewModel instance is created before promises queued on Context are finished. Results in error in VM constructor if trying to access properties of the Context that would have been set by a callback from a promise.
 `component: {
        viewModel: ComponentViewModel,
        template: template
    }`

**Comment by caseyWebb** [comment]
When you say queued, you mean passed to `ctx.queue`, right? If so, it does not wait for those. You will need to unqueue them if they are needed by the component, or use the `init` plugin.

**Comment by gandrisl** [comment]
Yes I've meant `ctx.queue`. Thank you, for such a detailed explanation and guidance!
