### ISSUE TITLE
Router Init Plugin - Initializing before rendering

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/knockout-contrib#98]
Hey Casey,

I'm using the Init plugin and in the documentation it is mentioned that it can be used "to declaratively initialize a viewModel before rendering."

Following the [documentation](https://github.com/Profiscience/knockout-contrib/tree/master/packages/router.plugins.init) I've added it to my ViewModel as follows:

```
import ko from "knockout";
import { Route } from "@profiscience/knockout-contrib-router";
import {
  initializerPlugin,
  INITIALIZED
} from "@profiscience/knockout-contrib-router-plugins-init";
import { componentPlugin } from "@profiscience/knockout-contrib-router-plugins-component";
import "regenerator-runtime/runtime";

Route.usePlugin(componentPlugin).usePlugin(initializerPlugin); // **MUST** come after component plugin


function resolveAfter2Seconds() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

class DataModel {
  constructor() {
    this[INITIALIZED] = this.init();
    this.init = this.init.bind(this);
  }
  async init() {
    console.log('calling Data Model init');
    await resolveAfter2Seconds();
  }
}

export default class ViewModel {
  constructor(ctx) {
    this.ctx = ctx;
    let user = ctx.params.id
      ? ctx.$parent.users.find(user => user.id === parseInt(ctx.params.id))
      : {};
    this.user = user;
    
    this.isInitialized = ko.observable(false);
    this.data = new DataModel()
    this[INITIALIZED] = this.init(ctx);
    this.init = this.init.bind(this);
  }

  init(ctx) {
    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        console.log('calling ViewModel init');
        this.isInitialized(true);
        resolve();
      }, 2000);
    });
    return p;
  }
}

```

When I run this code, I can see the delay between the call to the _init_ on my **DataModel** and the _init_ on my **ViewModel**.

Nevertheless, the component is rendered without waiting for the init methods to finish.

My expectation was that it would only render after finishing the initialization on both (DataModel and ViewModel).

Can you help me out understanding it?

Here is a [sample on CodeSandBox](https://wkpl01zzq5.codesandbox.io/user/new/)

Thanks in advance

**Comment by carlosagsmendes** [comment]
Thank you for the guidance.

I've moved the initialization code to the top of my base index.js file (simulating a bootstrap-routing.js):

```
window.ko = ko;
ko.options.deferUpdates = true;

Router.use(loadingMiddleware);
Route.usePlugin(componentPlugin)
      .usePlugin(initializerPlugin); // **MUST** come after component plugin
```
But now it doesn't even load the components. 

Here's the link to the codesandbox source:

https://codesandbox.io/s/wkpl01zzq5

**Comment by caseyWebb** [comment]
@carlosagsmendes Would you mind trying this with the latest rc (`npm install @profiscience/knockout-contrib@rc`  or `yarn add @profiscience/knockout-contrib@rc`)

**Comment by carlosagsmendes** [comment]
It looks fine. Thank you!
